import React, { createContext, useContext, useState, useEffect } from "react";

const fonts = {
  en: "'Libre Baskerville', cursive",
  mk: "'PT Serif', cursive",
};

const translations = {
  en: {
    english: "English",
    macedonian: "Macedonian",
    order_online_call: "Order Online Call",
    signup_login: "Sign up",
    title: "Kika Makeup and Beauty Academy",
    spring_summer: "Discover Your Beauty",
    find_your_style:
      "Get ready for 2025 with our curated makeup collection – bold shades, luxurious textures, and a glow that lasts.",
    shop_now: "Shop Now",
    men_collection: "Kika Makeup and Beauty Academy",
    sport_collection: "Kika Makeup and Beauty Academy",
    women_collection: "Kika Makeup and Beauty Academy",
    feeling_relax_day: "Feeling relax day, <br /> Enjoy weekend",
    home: "Home",
    shop: "Shop",
    checkout: "Checkout",
    my_account: "My Account",
    login_register: "Login Register",
    about_us: "About Us",
    contact_us: "Contact Us",
    faq: "F.A.Q",
    see_more: "More ...",
    read_more: "Read more",
    free_shipping: "DISCOUNT",
    free_shipping_description: "On all orders over € 50",
    free_returns: "FREE RETURNS",
    free_returns_description: "30 days money back guarantee",
    secure_payment: "SECURE PAYMENT",
    brand_name: "kikamakeupandbeautyacademy",
    all_rights_reserved: "All Rights Reserved",
    about: "ABOUT",
    about_us: "About us",
    store_location: "Store location",
    contact: "Contact",
    orders_tracking: "Orders tracking",
    useful_links: "Useful links",
    returns: "Returns",
    support_policy: "Support Policy",
    size_guide: "Size guide",
    faqs: "FAQs",
    follow_us: "Follow us on",
    subscribe: "Subscribe.",
    subscribe_message:
      "Subscribe to our newsletter to receive news on updates.",
    email_placeholder: "Your email address",
    contact_title: "Contact",
    home: "Home",
    contact: "Contact",
    contact_detail: "Contact detail",
    come_have_a_look: "COME HAVE A LOOK",
    address: "Address",
    address_details: "Bul. Turisticka 40, Ohrid - Macedonia 6000",
    contact: "Contact",
    mobile: "Mobile",
    phone: "Phone",
    mail: "Mail",
    hours_of_operation: "Hour of operation",
    monday_to_friday: "Monday – Friday",
    weekend_hours: "Sunday & Saturday",
    get_in_touch: "Get in touch",
    first_name: "First Name *",
    email: "Email *",
    subject: "Subject",
    message: "Message",
    submit: "Submit",
    about_page_title: "About",
    home: "Home",
    about: "About",
    simply_or_white: "Soft look or dramatic style – Your inspiration, our challenge",
    clever_unique_ideas: "Creativity, innovation, and professionalism in the world of beauty",
    about_page_description: "About us - Kika Makeup and Beauty Academy",
    store: "STORE",
    our_story: "OUR STORY",
    our_story_link: "OUR STORY",
    address: "Address",
    address_value: "Bul. Turisticka 40, Ohrid - Macedonia 6000",
    phone: "Phone",
    mobile: "Mobile",
    email: "Email",
    email_value: "makeupbykika@hotmail.com",
    about_page_extra_description:
      "Welcome to Kika Makeup and Beauty Academy, a place where creativity, innovation, and professionalism come together to prepare the future experts in the beauty industry. Our mission is to provide our students with the best training and practical skills to set them on the path to success. As an academy dedicated to makeup and beauty, we offer comprehensive courses that cover not only the basics of makeup but also advanced techniques that are current in the global market. Our program is designed to inspire the creative potential of our students and develop them into highly qualified professionals capable of tackling any challenge in the industry. At Kika Makeup and Beauty Academy, we value an individualized approach and strive to create a motivating and inspiring environment for every student. Our courses focus on the development of makeup techniques as well as the importance of confidence and creativity, which are crucial for building successful careers in this dynamic industry. Whether you aspire to become a professional makeup artist, a beautician, or to refine your skills in the latest beauty trends, our academy is here to guide you on that journey and provide you with the highest training standards.",
    online_store: "online store",
    testimonial_title: "Testimonial",
    our_brands_title: "Our Brands",
    about_us_title: "About Us",
    about_us_description:
      "At Kika Makeup and Beauty Academy, we are dedicated to inspiring creativity, delivering excellence, and empowering future beauty professionals. Our academy offers comprehensive training in timeless makeup techniques and cutting-edge beauty skills, ensuring our students are prepared for success in a dynamic industry. We focus on nurturing talent and fostering confidence, helping individuals build lasting careers in the world of makeup and beauty.",
    showing: "Showing",
    of: "of",
    result: "result",
    default: "Default",
    price_high_to_low: "Price - High to Low",
    price_low_to_high: "Price - Low to High",
    filter: "Filter",
    categories: "Services",
    all_categories: "All services",
    no_categories_found: "No categories found",
    colors: "Colors",
    no_colors_found: "No colors found",
    sizes: "Sizes",
    all_sizes: "All sizes",
    no_sizes_found: "No sizes found",
    tags: "Tags",
    no_tags_found: "No tags found",
    training: "Training",
    makeup: "Makeup",
    waxing: "Waxing",
    pedicure: "Pedicure",
    extras: "Extras",
    searchPlaceholder: "Search ...",
    allCategories: "All categories",
    noCategories: "No categories found",
    colors: "Colors",
    clearFilter: "x",
    noColors: "No colors found",
    popularProducts: "Popular products",
    noPopularProducts: "No products found",
    tags: "Tags",
    noTags: "No tags found",
    added_to_wishlist: "Added to wishlist",
    add_to_wishlist: "Add to wishlist",
    added_to_compare: "Added to compare",
    removed_from_compare: "Removed From Compare",
    removed_from_wishlist: "Removed From Wishlist",
    removed_all_from_wishlist: "Removed All From Wishlist",
    item_decremented_from_cart: "Item Decremented From Cart",
    removed_from_cart: "Removed From Cart",
    removed_all_from_cart: "Removed All From Cart",
    add_to_compare: "Add to compare",
    quick_view: "Quick view",
    choose_language: "Choose Language",
    choose_currency: "Currency",
    search_here: "Search here",
    dashboard: "Dashboard",
    orders: "Orders",
    downloads: "Downloads",
    payment_method: "Payment Method",
    billing_address: "Billing Address",
    account_details: "Account Details",
    hello_user: "Hello, ",
    if_not: "If Not ",
    logout: "Logout",
    dashboard_intro:
      "From your account dashboard, you can easily check & view your recent orders, manage your shipping and billing addresses, and edit your password and account details.",
    order: "Order",
    date: "Date",
    status: "Status",
    total: "Total",
    action: "Action",
    pending: "Pending",
    view: "View",
    product: "Product",
    expire: "Expire",
    download: "Download",
    free_template: "Free Real Estate PSD Template",
    yes: "Yes",
    download_file: "Download File",
    customer_login: "Customer Login",
    home: "Home",
    login: "Login",
    welcome_back: "Great to have you back!",
    username_or_email: "Username or email address",
    password: "Password",
    remember_me: "Remember me",
    lost_password: "Lost your password?",
    register: "Register",
    no_account_register: "If you don’t have an account, register now!",
    email_address: "Email Address",
    email_placeholder: "Enter your email",
    password_placeholder: "Enter your password",
    dashboard_welcome:
      "This is your dashboard, where you can easily review your latest orders, manage your shipping and billing addresses, and update your password and profile information.",
    no_payment_saved: "You have not saved a payment method yet.",
    edit_address: "Edit address",
    last_name: "Last name",
    display_name: "Display name",
    email_address: "Email Address",
    password_change: "Change password",
    current_password: "Current password",
    new_password: "New password",
    confirm_password: "Confirm password",
    save_changes: "Save",

    shipping_information_title: "Reservation Information",
    shipping_question_1: "How Can I Make a Reservation?",
    shipping_question_2: "Do You Accept Reservations Internationally?",
    shipping_question_3: "",
    shipping_question_4: "How Can I Confirm My Reservation?",
    payment_information_title: "Payment Information",
    payment_question_1: "What payment methods do you accept?",
    payment_question_2: "What Happens If There Is A Pricing Error?",
    payment_question_3: "What Do You Do With My Information?",
    orders_and_returns_title: "Reservations and Changes",
    orders_question_1: "How do I make a Reservation?",
    orders_question_2: "How Can I Review or Modify My Reservation?",
    orders_question_3: "Who Should I Contact If I Have Any Questions?",

    shipping_answer_1: "You can make a reservation by selecting the desired service and appointment time. Then, enter your personal and contact details to confirm your booking.",
    shipping_answer_2: "Currently, we only accept reservations in Macedonia. For any inquiries, please contact our customer support team via email or phone: Email: makeupbykika@hotmail.com, Phone: (+389) 78 / 343 - 377.",
    shipping_answer_3: "",
    shipping_answer_4: "To confirm your reservation or for additional information, please contact our team via the provided email or phone. We will assist you in finalizing the process quickly and easily.",
  
    payment_answer_1: "We gladly accept Visa, MasterCard, and American Express. Please note: if your card is issued outside Macedonia, additional verification may be required. All reservations must be paid in full when confirmed.",
    payment_answer_2: "We do our best to provide accurate pricing and service details, but errors may occasionally occur. If a pricing error happens, we reserve the right to correct it. You’ll be notified immediately, and any authorized payments will be adjusted or refunded.",
    payment_answer_3: "We use your information only to process your reservation quickly and securely, and to improve your experience. We respect your privacy and never share your details, except when necessary to complete your booking. For more information, please see our Privacy Policy.",
  
    orders_answer_1: "To make a reservation, select a service and add it to the cart. Then, enter your personal and contact information (first name, last name, address, email, phone) and choose an appointment date and time. Finally, select a payment method and confirm your reservation by clicking the ‘Place Order’ button.",
    orders_answer_2: "In the cart you can review your reservation before proceeding to checkout. You will see the selected services or products with their quantity and price. You can apply a discount code, update the quantity, or empty the cart completely. Once ready, click the “Checkout” button to finalize your reservation.",
    orders_answer_3: "Once you contact our team via the provided email or phone number, we will assist you in choosing the most suitable appointment.",

    checkout_title: "Checkout",
    home: "Home",
    billing_address: "Billing Address",
    first_name_label: "First Name",
    first_name_placeholder: "Enter your first name",
    last_name_label: "Last Name",
    last_name_placeholder: "Enter your last name",
    email_label: "Email Address",
    email_placeholder: "Enter your email address",
    phone_label: "Phone Number",
    phone_placeholder: "Enter your phone number",
    company_label: "Company",
    company_placeholder: "Enter your company name",
    address_label: "Address",
    address_line1_placeholder: "Enter address line 1",
    address_line2_placeholder: "Enter address line 2",
    country_label: "Country",
    city_label: "City",
    city_placeholder: "Enter your city",
    state_label: "State",
    state_placeholder: "Enter your state",
    zip_label: "Zip Code",
    zip_placeholder: "Enter your zip code",
    country_bangladesh: "Macedonia",
    country_china: "China",
    country_australia: "Australia",
    country_india: "India",
    country_japan: "Japan",
    cart_total: "Cart Total",
    product_label: "Product",
    total_label: "Total",
    subtotal_label: "Subtotal",
    shipping_fee_label: "Shipping Fee",
    grand_total_label: "Grand Total",
    payment_method: "Payment Method",
    payment_check: "Check Payment",
    payment_bank: "Bank Transfer",
    payment_cash: "On-site Payment",
    payment_paypal: "PayPal",
    payment_payoneer: "Payoneer",
    accept_terms_label: "I have read and agree to the terms and conditions",
    place_order: "Place Order",
    cart_empty_message: "No items found in cart to checkout",
    compare: "Compare",
    compare_page_title: "Compare",
    home: "Home",
    compare: "Compare",
    product_info: "Product Info",
    remove_product: "Remove Product",
    buy_now: "Buy Now",
    select_option: "Select Option",
    added: "Added",
    add_to_cart: "Add to Cart",
    out_of_stock: "Out of Stock",
    price: "Price",
    description: "Description",
    not_available: "N/A",
    rating: "Rating",
    no_items_to_compare: "No items to compare",
    add_items: "Add Items",
    cart_title: "Cart",
    color: "Color",
    size: "Size",
    subtotal: "Subtotal:",
    view_cart: "View Cart",
    checkout: "Checkout",
    free_shipping_text: "Discount on All Orders Over € 50!",
    no_items_found_in_cart: "No items found in cart",
    wishlist_title: "Wishlist",
    view_wishlist: "View Wishlist",
    no_items_in_wishlist: "No items found in wishlist",
    home: "Home",
    product: "Product",
    price: "Price",
    clear_wishlist: "Clear Wishlist",
    no_items_found: "No items found in wishlist",
    added_to_cart: "Added to cart",
    out_of_stock: "Out of stock",
    select_option: "Select option",
    buy_now: "Buy now",
    color: "Color",
    size: "Size",
    cart: "Cart",
    home: "Home",
    product: "Product",
    price: "Price",
    quantity: "Quantity",
    total: "Total",
    color: "Color",
    size: "Size",
    enter_coupon_code: "Enter your coupon code",
    apply_coupon: "Apply coupon",
    clear_cart: "Clear cart",
    cart_totals: "Cart totals",
    subtotal: "Subtotal",
    proceed_to_checkout: "Proceed to checkout",
    no_items_in_cart: "No items found in cart",
    search_products_placeholder: "Search ...",
    search_hint: "# Hit enter to search",
    out_of_stock: "Out of Stock",
    select_option: "Select Option",
    buy_now: "Buy Now",
    share: "Share",
    new: "new",
    out: "out",
    sku: "SKU",
    click_to_enlarge: "Click to enlarge",
    additional_information: "Additional Information",
    reviews: "Reviews",
    reviews_on: "reviews on",
    add_review: "Add Review",
    email_privacy_notice:
      "Your email address will not be published. Required fields are marked *",
    name: "Name",
    email: "Email",
    your_rating: "YOUR RATING",
    your_review: "Your Review",
    submit: "Submit",
    size: "Size",
    color: "Color",
    customer_reviews: "Customer Reviews",
    currency: "€ ",
    cookies:
      "We use cookies to improve your experience on our site. By accepting, you agree to our use of cookies. For more information, read our Terms of Service and Privacy Policy.",
    accept: "Accept",
    continue_with_google: "Continue with Google",
    continue_with_facebook: "Continue with Facebook",
    or: "or",
    registration_success: "Registered successfully",
    login_success: "Login successfully",
    please_verify_email: "Please verify your email address",
    logout_success: "You have successfully logged out.",
    profile_updated: "Profile updated successfully",
    password_note:
      "**You can change only your password if you are logged in with user/pass. If you are logged in with other providers such as Google, your password must be changed in their respective account settings.",
    password_mismatch: "The passwords do not match. Please try again.",
    password_strength: "The password must be at least 6 characters long.",
    email_sending: "Email sent successfully!",
    thank_you_for_subscribing: "Thank you for subscribing!",
    email_subject: "Welcome to Kika Makeup and Beauty Academy!",
    preview: "Welcome to Kika Makeup and Beauty Academy!",
    greeting: "Hi,",
    welcomeMessage:
      "Thank you for subscribing to Kika Makeup and Beauty Academy. We are excited to help you explore the world of makeup and beauty. Stay tuned for exclusive tips, tutorials, and offers!",
    getStarted: "Get started",
    bestRegards: "Best,",
    team: "The Kika Makeup and Beauty Academy Team",
    footer: "@ Kika Makeup and Beauty Academy, Ohrid 6000, Macedonia",
    sending: "Sending...",
    forgot_password: "Forgot Password?",
    reset_email_sent: "Reset email sent successfully!",
    please_enter_your_email_first: "Please enter your email address first",
    password_too_short: "Password is too short",
    please_enter_your_password: "Please enter your password",
    invalid_email_format: "Invalid email format",
    you_have_not_made_any_order_yet: "You have not made any order yet.",
    you_have_not_downloaded_any_file_yet:
      "You have not downloaded any file yet.",
    reset_password_for: "Reset Password for ",
    reset_password: "Reset Password",
    password_reset_success: "Password reset successful!",
    passwords_do_not_match: "Passwords do not match",
    please_enter_your_name: "Please enter your name.",
    please_enter_your_email: "Please enter your email.",
    please_enter_a_subject: "Please enter a subject.",
    please_enter_a_message: "Please enter a message.",
    message_too_short: "Message is too short.",
    you_must_be_logged_in: "You must be logged in to perform this action.",
    review_submitted_successfully: "Review submitted successfully!",
    please_give_a_rating: "Please give a rating.",
    please_log_in_to_place_order: "Please log in to place an order.",
    delete: "Delete",
    please_select_payment_method: "Please select a payment method.",
    please_accept_terms: "Please accept terms and conditions.",
    order_placed_successfully: "Order placed successfully!",
    name_on_card: "Name on Card",
    enter_name_on_card: "Enter name on card",
    card_number: "Card Number",
    enter_card_number: "Enter card number",
    expiration: "Expiration",
    MM_YY: "MM/YY",
    CVC: "CVC",
    enter_cvc: "Enter CVC",
    payment_information: "Payment Information",
    nameOnCard: "Name on Card is required.",
    cardNumber: "Invalid card number.",
    invalid_expiration:
      "Invalid expiration date. Use MM/YY format and ensure the card is not expired.",
    invalid_cvc: "Invalid CVC. It should be 3 or 4 digits.",
    reservation_datetime_title: "Reservation",
    reservation_datetime_description:
      "Please book an appointment for your service. We will contact you to confirm your reservation.",
    reservation_date_label: "Date",
    reservation_time_label: "Time",
    date_of_reservation: "Reservation",
    time_of_reservation: "Time",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Canceled",
    choose_time: "Choose Time",
    cancel: "Cancel",
    ok: "OK",
    choose_date: "Choose Date",
    user: "User",
    order_deleted: "Order deleted!",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",     
    terms_of_service_register: "Terms of Service",   
    privacy_intro: "We respect your privacy and are committed to protecting your personal data. When you shop with us, we only collect information necessary to process orders, improve your experience, and provide customer support.",
    information_we_collect: "Information We Collect",
    info_collect_name_email: "- Name, email, phone, and shipping address when placing an order.",
    info_collect_payment_details: "- Payment details (processed securely via third-party payment systems).",
    info_collect_optional: "- Additional information you voluntarily provide, such as preferences or account details.",
    how_we_use_your_information: "How We Use Your Information",
    use_order_processing: "- To process and deliver your orders.",
    use_communication: "- To communicate about orders, promotions, or news.",
    use_improvement: "- To improve products, services, and website experience.",
    how_we_protect_your_information: "How We Protect Your Information",
    protect_info_text: "We use security systems and follow industry standards to protect your data. We never sell, rent, or share your information with third parties, except when necessary to complete an order (e.g., delivery or payment).",
    your_rights: "Your Rights",
    your_rights_text: "You may request access, correction, or deletion of your personal data at any time by contacting us at:",
    terms_of_service: "Terms of Service",
    tos_intro: "Welcome to Kika Makeup Academy. By accessing or using our website and services, you agree to comply with these Terms of Service. Please read them carefully before using our platform.",
    user_responsibilities: "User Responsibilities",
    user_responsibility_1: "- You are responsible for all activities performed under your account.",
    user_responsibility_2: "- You must not use the website for any unlawful or prohibited purpose.",
    user_responsibility_3: "- You must provide accurate and up-to-date information when registering or placing orders.",
    account_security: "Account and Security",
    account_security_1: "- Keep your account credentials secure and confidential.",
    account_security_2: "- Notify us immediately if you suspect unauthorized access to your account.",
    orders_payments: "Orders and Payments",
    orders_payments_1: "- All orders are subject to acceptance and availability.",
    orders_payments_2: "- Payments are processed securely through third-party providers.",
    orders_payments_3: "- You are responsible for any taxes, duties, or fees related to your purchases.",
    changes: "Changes to Terms",
    changes_text: "Kika Makeup Academy may update these Terms of Service at any time. Continued use of our services constitutes acceptance of the updated terms.",
    limitation_of_liability: "Limitation of Liability",
    limitation_text: "Kika Makeup Academy is not liable for indirect, incidental, or consequential damages arising from the use of our website or services.",
    governing_law: "Governing Law",
    governing_law_text: "These Terms of Service are governed by the laws of North Macedonia. Any disputes will be resolved in accordance with applicable law.",
    contact: "Contact",
    contact_text: "For any questions about these Terms of Service, please contact us at: ",
    back_to_account: "Back to My Account",    
    invalid_credentials: "Incorrect email or password.",
    user_not_found: "No account found with this email.",
    email_in_use: "This email is already registered.",
    too_many_requests: "Too many attempts. Please try again later.",
    network_error: "Network error. Check your connection.",
    something_went_wrong: "Something went wrong. Please try again.",
    coupon_discount: "Discount",
    coupon_applied: "Coupon applied successfully!",
    order_preview: "Order Preview",
    back_home: "Home",
    comingSoon: "Website Coming Soon",
    confirm_deletion: "Confirm Deletion",
    are_you_sure_delete_order: "Are you sure you want to delete this order?",
    yes_delete: "Yes, Delete",
    financial_reports: "Financial Reports",
    revenue_by_payment_method: "Revenue by Payment Method",
    revenue_by_status: "Revenue by Status",
    payment_cash: "On-site Payment",
    select_country: "Select Country",
    select_city: "City / Town",
    confirm_logout: "Logout",
    are_you_sure_logout: "Are you sure you want to logout?",
    yes_logout: "Yes, Logout",
    financial_reports: "Financial Reports",
    total_orders: "Total Orders",
    total_revenue: "Total Revenue",
    avg_order_value: "Avg Order Value",
    order_success_rate: "Order Success Rate",
    daily_revenue_trend: "Daily Revenue Trend",
    last_7_days: "Last 7 Days",
    last_30_days: "Last 30 Days",
    last_90_days: "Last 90 Days",
    monthly_revenue: "Monthly Revenue",
    yearly_comparison: "Yearly Comparison",
    top_products: "Top Services",
    product_name: "Service Name",
    quantity_sold: "Quantity Sold",
    revenue: "Revenue",
    download_pdf: "Download PDF",
    preparing_pdf: "Preparing PDF...",
    generated_on: "Generated on",
    generated_by: "Generated by Your Company Name",
    all_time_orders: "All time orders",
    gross_revenue: "Gross revenue",
    per_order_average: "Per order average",
    confirmed: "Confirmed",
    confirmed_analysis: "Confirmed",
    analysis: "Analysis",
    daily_revenue_description: "Shows revenue trends over the selected period",
    monthly_revenue_description: "Monthly revenue breakdown for the selected year",
    yearly_comparison_description: "Year-over-year revenue comparison",
    top_products_description: "Best selling products ranked by total revenue generated",
    revenue_by_status_description: "Shows revenue distribution based on order status",
    revenue_by_payment_method_description: "Shows revenue distribution based on payment methods used",
    payment_method: "Payment Method",
    amount: "Amount",
    count: "Count",
    avg_price: "Avg. Price",
    detailed_daily_breakdown: "Detailed Daily Breakdown",
    days: "days",
    date: "Date",
    orders: "Orders",
    revenue: "Revenue",
    total: "Total",
    avg_daily_revenue: "Avg. Daily Revenue",
    best_day: "Best Day",
    avg_orders_per_day: "Avg. Orders/Day",
    detailed_monthly_breakdown: "Detailed Monthly Breakdown",
    months: "months",
    month: "Month",
    orders: "Orders",
    revenue: "Revenue",
    avg_per_day: "Avg. per Day",
    total: "Total",
    avg_monthly_revenue: "Avg. Monthly Revenue",
    best_month: "Best Month",
    total_orders_year: "Total Orders (Year)",
    avg_monthly_orders: "Avg. Monthly Orders",
    detailed_yearly_breakdown: "Detailed Yearly Breakdown",
    years: "years",
    year: "Year",
    orders: "Orders",
    revenue: "Revenue",
    growth: "Growth",
    avg_monthly: "Avg. Monthly",
    total: "Total",
    total_years: "Total Years",
    best_year: "Best Year",
    avg_yearly_revenue: "Avg. Yearly Revenue",
    overall_growth: "Overall Growth",
    previous: "Prev.",
    next: "Next",
    showing: "Showing",
    to: "to",
    of: "of",
    orders: "Orders",
    search: "Search",
    search_orders: "Search orders...",
    filter_by_status: "Status",
    all_statuses: "All statuses",
    search_order_or_user: "Search order or user...",
    filter_by_payment: "Payment method",
    all_payments: "All payments",
    filter_by_year: "Year",
    all_years: "All years",
    please_confirm_your_password: "Please confirm your password before continuing.",
    password_must_contain_letter_and_number: "The password must contain at least one upper letter and one number.",
    please_enter_your_first_name: "Please enter your first name.",
    please_enter_your_last_name: "Please enter your last name.",
    first_name_too_short: "First name must be at least 2 characters.",
    last_name_too_short: "Last name must be at least 2 characters.",
    i_accept: "I accept the ",
    and: " and ",
    coupon_min_total: "Cart total must exceed 48.67 € to apply coupon",
    users: "Users",    
    total_users: "Total Users",
    no_users_found: "No users found",
    search_user_name_email: "Search by name or email...",
    filter_by_role: "Role",
    all_roles: "All Roles",
    name: "Name",
    phone: "Phone",
    city: "City",
    country: "Country",
    admins: "Admins",
    guests: "Guests",
    role: "Role",
    coupon: "Coupon",
    admin: "Admin",
    guest: "Guest",
    continue_with_phone: "Continue with Phone",
    enter_your_phone_number: "Enter your phone number",
    enter_verification_code: "Enter the verification code"
  },
  mk: {
    english: "Англиски",
    macedonian: "Македонски",
    order_online_call: "Нарачајте онлајн",
    signup_login: "Најавете се",
    title: "Кика - Академија за Шминка и Убавина",
    spring_summer: "Откријте ја вашата природна убавина",
    find_your_style: "Подгответе се за 2025 со нашиот избор на шминка – впечатливи нијанси, луксузни текстури и сјај кој трае.",
    shop_now: "Купувај сега",
    men_collection: "Кика - Академија за Шминка и Убавина",
    sport_collection: "Кика - Академија за Шминка и Убавина",
    women_collection: "Кика - Академија за Шминка и Убавина",
    feeling_relax_day: "Опуштен ден, <br /> Уживајте за викендот",
    home: "Дома",
    shop: "Продавница",
    checkout: "Плаќање",
    my_account: "Мој Профил",
    login_register: "Најавете се",
    about_us: "За Нас",
    contact_us: "Контакт",
    faq: "Најчесто поставувани прашања",
    see_more: "Повеќе",
    read_more: "Прочитај повеќе",
    free_shipping: "Попуст",
    free_shipping_description: "На сите нарачки над 2999 ден.",
    free_returns: "Бесплатно враќање",
    free_returns_description: "Гаранција за поврат на парите во рок од 30 дена",
    secure_payment: "Безбедно плаќање",
    brand_name: "kikamakeupandbeautyacademy",
    all_rights_reserved: "Сите права се задржани",
    about: "ЗА НАС",
    about_us: "За нас",
    store_location: "Локација на продавница",
    contact: "Контакт",
    orders_tracking: "Следење на нарачки",
    useful_links: "Линкови",
    returns: "Враќања",
    support_policy: "Политика за поддршка",
    size_guide: "Водич за големини",
    faqs: "Најчесто поставувани прашања",
    follow_us: "Следете не на",
    subscribe: "Претплатете се.",
    subscribe_message:
      "Претплатете се на нашиот весник за да добивате новости.",
    email_placeholder: "Вашата email адреса",
    contact_title: "Контакт",
    home: "Дома",
    contact: "Контакт",
    contact_detail: "Детали за контакт",
    come_have_a_look: "Дојдете и погледнете",
    address: "АДРЕСА",
    address_details: "Бул. Туристичка 40, Охрид - Македонија 6000",
    contact: "Контакт",
    mobile: "Мобилен",
    phone: "Телефон",
    mail: "Пошта",
    hours_of_operation: "Работно време",
    monday_to_friday: "Понеделник – Петок",
    weekend_hours: "Недела & Сабота",
    get_in_touch: "Контактирајте не",
    first_name: "Име *",
    email: "Е-маил *",
    subject: "Тема",
    message: "Порака",
    submit: "Испрати",
    about_page_title: "За нас",
    home: "Дома",
    about: "За нас",
    simply_or_white: "Нежен изглед или драматичен стил – Ваша инспирација, наш предизвик",
    clever_unique_ideas: "Креативност, иновација и професионализам во светот на убавината",
    about_page_description: "За нас - Кика Makeup and Beauty Academy",
    store: "Дома",
    our_story: "Нашата приказна",
    our_story_link: "Нашата приказна",
    address: "Адреса",
    address_value: "Бул. Туристичка 40, Охрид - Македонија 6000",
    phone: "Телефон",
    mobile: "Мобилен",
    email: "Е-маил",
    email_value: "makeupbykika@hotmail.com",
    about_page_extra_description:
      "Добредојдовте во Кика Makeup and Beauty Academy, место каде што креативноста, иновацијата и професионализмот се комбинираат за да ги подготвиме идните експерти во индустријата за убавина. Наша мисија е да им овозможиме на нашите студенти најдобра обука и практични вештини кои ќе ги постават на патот кон успехот. Како академија посветена на шминкањето и убавината, нудиме сеопфатни курсеви кои опфаќаат не само основите на шминкањето, туку и напредни техники кои се актуелни на глобалниот пазар. Нашата програма е дизајнирана да ги поттикне креативните потенцијали на нашите студенти и да ги развие во високо квалификувани професионалци кои можат да се справат со секој предизвик во индустријата. Во Кика Makeup and Beauty Academy, го цениме индивидуалниот пристап и се стремиме да создадеме поттикнувачка и инспиративна средина за секој студент. Нашите курсеви се фокусирани на развојот на техниките за шминкање, како и на важноста на самодовербата и креативноста, што е клучно за градење успешни кариера во оваа динамична индустрија. Без разлика дали сакате да станете професионален шминкер, козметичар или да се усовршите во најновите трендови на убавина, нашата академија е тука за да ве води на тој пат и да ви овозможи највисоките стандарди на обука.",
    online_store: "онлајн продавница",
    testimonial_title: "Лични искуства",
    our_brands_title: "Брендови",
    about_us_title: "За Нас",
    about_us_description:
      "Добредојдовте во Кика Makeup and Beauty Academy, место каде што креативноста, иновацијата и професионализмот се комбинираат за да ги подготвиме идните експерти во индустријата за убавина. Наша мисија е да им овозможиме на нашите студенти најдобра обука и практични вештини кои ќе ги постават на патот кон успехот. Како академија посветена на шминкањето и убавината, нудиме сеопфатни курсеви кои опфаќаат не само основите на шминкањето, туку и напредни техники кои се актуелни на глобалниот пазар.",
    showing: "Прикажани",
    of: "од",
    result: "резултати",
    default: "Стандардно",
    price_high_to_low: "Цена - Од висока до ниска",
    price_low_to_high: "Цена - Од ниска до висока",
    filter: "Филтер",
    all_categories: "Сите услуги",
    no_categories_found: "Нема услуги",
    colors: "Бои",
    no_colors_found: "Нема бои",
    sizes: "Големини",
    all_sizes: "Сите големини",
    no_sizes_found: "Нема големини",
    tags: "Тагови",
    no_tags_found: "Нема тагови",
    training: "Обуки",
    makeup: "Шминка",
    waxing: "Депилација",
    pedicure: "Педикир",
    extras: "Дополнителни услуги",
    searchPlaceholder: "Пребарување на услуги ...",
    categories: "Услуга",
    allCategories: "Сите услуги",
    noCategories: "Нема услуги",
    colors: "Бои",
    clearFilter: "x",
    noColors: "Нема бои",
    popularProducts: "Популарни услуги",
    noPopularProducts: "Нема услуги",
    tags: "Ознаки",
    noTags: "Нема ознаки",
    added_to_wishlist: "Додадено во омилени",
    add_to_wishlist: "Додади во омилени",
    added_to_compare: "Додадено за споредба",
    removed_from_compare: "Отстрането од споредба",
    removed_from_wishlist: "Отстрането од омилени",
    removed_all_from_wishlist: "Омилените услуги се избришани",
    item_decremented_from_cart: "Ставката е намалена во кошничка",
    removed_from_cart: "Отстрането од кошничката",
    removed_all_from_cart: "Кошничката е испразнета",
    add_to_compare: "Додади за споредба",
    quick_view: "Брз преглед",
    choose_language: "Изберете јазик",
    choose_currency: "Валута",
    search_here: "Пребарувај тука",
    dashboard: "Контролна табла",
    orders: "Нарачки",
    download: "Преземи",
    payment: "Плаќање",
    address: "Адреса",
    account_details: "Детали за профилот",
    hello: "Здраво",
    if_not: "Ако не е",
    logout: "Одјави се",
    dashboard_welcome:
      "Ова е вашата контролна табла, можете лесно да ги прегледате вашите најнови нарачки, да управувате со адресите за испорака и фактурирање, како и да ги ажурирате вашата лозинка и податоците за профилот.",
    order: "Нарачка",
    date: "Датум",
    status: "Статус",
    total: "Вкупно",
    action: "Акција",
    view: "Прегледај",
    product: "Услуга",
    expire: "Истекува",
    download_file: "Преземи датотека",
    payment_method: "Начин на плаќање",
    no_payment_saved: "Сè уште немате зачувано начин на плаќање.",
    billing_address: "Адреса за фактурирање",
    mobile: "Мобилен",
    edit_address: "Уреди адреса",
    first_name: "Име",
    last_name: "Презиме",
    display_name: "Име за прикажување",
    email_address: "Е-маил",
    password_change: "Промена на лозинка",
    current_password: "Тековна лозинка",
    new_password: "Нова лозинка",
    confirm_password: "Потврди лозинка",
    save_changes: "Зачувај",
    customer_login: "Најава",
    home: "Дома",
    login: "Најава",
    welcome_back: "Добредојдовте повторно!",
    username_or_email: "Корисничко име или е-адреса",
    password: "Лозинка",
    remember_me: "Запомни ме",
    lost_password: "Ја заборавивте лозинката?",
    register: "Регистрирај се",
    no_account_register: "Ако немате профил, регистрирајте се сега!",
    email_address: "Е-маил",
    email_placeholder: "Внесете ја вашата е-маил",
    password_placeholder: "Внесете ја вашата лозинка",
    hello_user: "Здраво, ",
    not_you: "Ако не си {name}",

    shipping_information_title: "Информации за резервации",
    shipping_question_1: "Како можам да направам резервација?",
    shipping_question_2: "Дали можам да направам резервација од странство?",
    shipping_question_3: "",
    shipping_question_4: "Како да проверам дали мојата резервација е потврдена?",
    payment_information_title: "Информации за плаќање",
    payment_question_1: "Кои методи за плаќање ги прифаќате?",
    payment_question_2: "Што се случува ако има грешка во цените?",
    payment_question_3: "Што правите со моите информации?",
    orders_and_returns_title: "Резервации и откажување",
    orders_question_1: "Како да направам резервација?",
    orders_question_2: "Како можам да ја откажам или сменам мојата резервација?",
    orders_question_3: "Кого треба да контактирам ако имам прашања?",
    shipping_answer_1:
      "Резервација можете да направите преку нашата веб-страница со избор на услуга и термин кој најмногу ви одговара. Ќе треба да ги внесете вашите контакт информации и да ја потврдите резервацијата.",
    shipping_answer_2:
      "Да, можете да направите резервација од било која локација. За дополнителни информации, контактирајте го нашиот тим за поддршка преку е-маил или телефон: makeupbykika@hotmail.com, Телефон: (+389) 78 / 343 - 377",
    shipping_answer_3:
      "",
    shipping_answer_4:
      "По завршување на резервацијата, ќе добиете е-маил со потврда и детали за вашиот термин. Доколку не ја добиете потврдата во рок од неколку минути, проверете ја папката за несакана пошта (spam) или контактирајте нè директно.",
    payment_answer_1:
      "Со задоволство прифаќаме Visa, MasterCard и American Express. Ако картичката е издадена надвор од Македонија, можно е да биде побарана дополнителна верификација. Не прифаќаме плаќање при испорака – сите нарачки мора да бидат платени онлајн при поднесување.",
    payment_answer_2:
      "Се стремиме кон точност во цените и описите, но понекогаш може да се појави грешка. Доколку има грешка во цената, го задржуваме правото да ја откажеме нарачката. Ќе бидете известени, а средствата ќе бидат веднаш рефундирани.",
    payment_answer_3:
      "Вашите информации ги користиме само за да ја обработиме вашата резервација брзо и безбедно и за да го подобриме вашето искуство. Вашата приватност е важна за нас и никогаш не ги споделуваме овие информации, освен кога е неопходно за испорака. Повеќе детали може да најдете во нашата политика за приватност.",
    orders_answer_1:
      "За да направите резервација, изберете услуга и додадете ја во кошничката. Потоа внесете ги вашите лични и контакт информации (име, презиме, адреса, е-маил, телефон) и резервирајте термин со избор на датум и време. На крај изберете метод на плаќање и потврдете ја резервацијата со клик на копчето „Нарачај“.",
    orders_answer_2:
      "Во кошничката можете да ја прегледате вашата нарачка пред да продолжите со плаќање. Ќе ги видите избраните услуги или производи со нивната количина и цена. Имате можност да додадете промотивен код за попуст, да ја ажурирате количината или целосно да ја испразните кошничката. Кога ќе бидете подготвени, продолжете со копчето „Плаќање“ за финализирање на вашата резервација.",
    orders_answer_3:
      "Можете да го контактирате нашиот тим за поддршка на корисници преку е-маил или телефонски број. Ако не ви е погодно да зборувате, можете да дојдете и директно во нашата локација.",

    checkout_title: "Плаќање",
    home: "Дома",
    billing_address: "Фактурна адреса",
    first_name_label: "Име",
    first_name_placeholder: "Внесете го вашето име",
    last_name_label: "Презиме",
    last_name_placeholder: "Внесете го вашето презиме",
    email_label: "Емаил адреса",
    email_placeholder: "Внесете ја вашата емаил адреса",
    phone_label: "Телефонски број",
    phone_placeholder: "Внесете го вашиот телефонски број",
    company_label: "Компанија",
    company_placeholder: "Внесете го името на вашата компанија",
    address_label: "Адреса",
    address_line1_placeholder: "Внесете ја адресата (адреса 1)",
    address_line2_placeholder: "Внесете ја адресата (адреса 2)",
    country_label: "Држава",
    city_label: "Град",
    city_placeholder: "Внесете го вашиот град",
    state_label: "Држава/Област",
    state_placeholder: "Внесете ја вашата држава/област",
    zip_label: "Поштенски код",
    zip_placeholder: "Внесете го вашиот поштенски код",
    country_bangladesh: "Македонија",
    country_china: "Кина",
    country_australia: "Австралија",
    country_india: "Индија",
    country_japan: "Јапонија",
    cart_total: "Вкупна кошничка",
    product_label: "Услуга",
    total_label: "Вкупно",
    subtotal_label: "Подвкупно",
    shipping_fee_label: "Цена на испорака",
    grand_total_label: "Конечен износ",
    payment_method: "Начин на плаќање",
    payment_check: "Плаќање со чек",
    payment_bank: "Банкарски трансфер",
    payment_cash: "Плаќање на лице место",
    payment_paypal: "PayPal",
    payment_payoneer: "Payoneer",
    accept_terms_label: "Го прочитав и се согласувам со условите и правилата",
    place_order: "Нарачај",
    cart_empty_message: "Нема услуги во вашата кошничката",
    compare: "Споредба",
    compare_page_title: "Споредба",
    home: "Дома",
    compare: "Споредба",
    product_info: "Информации за услугата",
    remove_product: "Отстрани услуга",
    buy_now: "Купувај сега",
    select_option: "Избери опција",
    added: "Додадено",
    add_to_cart: "Додади во кошничка",
    out_of_stock: "Нема на залиха",
    price: "Цена",
    description: "Опис",
    not_available: "Нема",
    rating: "Оценка",
    no_items_to_compare: "Нема услуги за споредба",
    add_items: "Додади услуги",
    cart_title: "Кошничка",
    color: "Боја",
    size: "Големина",
    subtotal: "Вкупно:",
    view_cart: "Погледни кошничка",
    checkout: "Плаќање",
    free_shipping_text: "Попуст за нарачки над 2999 денари!",
    no_items_found_in_cart: "Нема услуги во кошничката",
    wishlist_title: "Омилени",
    view_wishlist: "Преглед на омилени услуги",
    no_items_in_wishlist: "Листата на омилени услуги е празна",
    home: "Дома",
    product: "Услуга",
    price: "Цена",
    clear_wishlist: "Исчисти",
    no_items_found: "Нема услуги во омилени",
    added_to_cart: "Додадено во кошничката",
    out_of_stock: "Нема на залиха",
    select_option: "Избери опција",
    buy_now: "Купувај веднаш",
    color: "Боја",
    size: "Големина",
    cart: "Кошничка",
    home: "Дома",
    product: "Услуга",
    price: "Цена",
    quantity: "Количина",
    total: "Вкупно",
    color: "Боја",
    size: "Големина",
    enter_coupon_code: "Внесете го кодот за попуст",
    apply_coupon: "Внесете попуст",
    clear_cart: "Испразни кошничка",
    cart_totals: "Вкупно",
    subtotal: "Пресметка",
    proceed_to_checkout: "Продолжи до наплата",
    no_items_in_cart: "Нема услуги во кошничката",
    search_products_placeholder: "Пребарај услуги...",
    search_hint: "# Притиснете Enter за пребарување",
    out_of_stock: "Нема на залиха",
    select_option: "Изберете опција",
    buy_now: "Купете веднаш",
    share: "Сподели",
    new: "ново",
    out: "нема",
    sku: "Код",
    click_to_enlarge: "Кликни за зголемување",
    additional_information: "Дополнителни информации",
    reviews: "Рецензии",
    reviews_on: "рецензии за",
    add_review: "Додади рецензија",
    email_privacy_notice:
      "Вашата email адреса нема да биде објавена. Потребните полиња се означени со *",
    name: "Име",
    email: "Email",
    your_rating: "ВАШАТА ОЦЕНА",
    your_review: "Ваша рецензија",
    submit: "Испрати",
    size: "Големина",
    color: "Боја",
    customer_reviews: "Рецензии од клиенти",
    currency: "ден.",
    cookies:
      "Користиме колачиња за да го подобриме вашето искуство на нашата веб-страница. Со прифаќањето, се согласувате со нашата употреба на колачиња. За повеќе информации, прочитајте ги нашите Услови за користење и Политика за приватност.",
    accept: "Прифати",
    continue_with_google: "Продолжете со Google",
    continue_with_facebook: "Продолжете со Facebook",
    or: "или",
    registration_success: "Регистрацијата е успешна",
    login_success: "Успешно се најавивте",
    please_verify_email:
      "Ве молиме, проверете ја вашата е-маил за да ја потврдите.",
    logout_success: "Успешно се одјавивте.",
    profile_updated: "Профилот е успешно ажуриран.",
    password_note:
      "**Можете да ја промените лозинката ако сте најавени со корисничко име и лозинка. Ако сте најавени со други провајдери како што се Google, вашата лозинка мора да се промени во нивните соодветни поставки за сметка.",
    password_mismatch: "Лозинките не се совпаѓаат. Обидете се повторно.",
    password_strength: "Лозинката мора да содржи најмалку 6 знаци.",
    email_sending: "Email-от е успешно испратен!",
    thank_you_for_subscribing: "Ви благодарам што се претплативте!",
    email_subject: "Добредојдовте во Kika Makeup and Beauty Academy!",
    preview: "Добредојдовте во Кика Makeup and Beauty Academy!",
    greeting: "Здраво,",
    welcomeMessage:
      "Ви благодариме што се претплативте на Кика Makeup and Beauty Academy. Возбудени сме што ќе ви помогнеме да го истражите светот на шминкањето и убавината. Следете нè за ексклузивни совети, туторијали и понуди!",
    getStarted: "Започни",
    bestRegards: "Со почит,",
    team: "Тимот на Кика Makeup and Beauty Academy",
    footer: "@ Кика Makeup and Beauty Academy, Охрид 6000, Македонија",
    sending: "Испраќање...",
    forgot_password: "Ја заборавивте лозинката?",
    reset_email_sent: "Email-от за промена на лозинката е успешно испратен!",
    please_enter_your_email_first: "Ве молам, внесете го вашиот е-маил.",
    password_too_short: "Лозинката мора да содржи најмалку 6 знаци.",
    please_enter_your_password: "Ве молам, внесете ја вашата лозинка.",
    invalid_email_format: "Внесете валидна е-маил.",
    you_have_not_made_any_order_yet: "Сè уште немате направено нарачка.",
    you_have_not_downloaded_any_file_yet: "Сè уште немате преземено датотека.",
    reset_password_for: "Промена на лозинка за ",
    reset_password: "Промени лозинка",
    password_reset_success: "Лозинката е успешно променета!",
    passwords_do_not_match: "Лозинките не се совпаѓаат. Обидете се повторно.",
    please_enter_your_name: "Ве молиме, внесете го вашето име.",
    please_enter_your_email: "Ве молам, внесете го вашиот е-маил.",
    please_enter_a_subject: "Ве молиме, внесете тема.",
    please_enter_a_message: "Ве молиме, внесете порака.",
    message_too_short: "Пораката е прекратка. Ве молиме, внесете подолга порака.",
    you_must_be_logged_in: "Мора да сте најавени за да објавете рецензија.",
    review_submitted_successfully: "Рецензијата е успешно испратена!",
    please_give_a_rating: "Ве молиме, доделете оценка.",
    please_log_in_to_place_order:
      "Ве молиме, најавете се за да направите нарачка.",
    delete: "Избриши",
    please_select_payment_method: "Ве молиме, изберете начин на плаќање.",
    please_accept_terms: "Ве молиме, прифатете ги условите и правилата.",
    order_placed_successfully: "Нарачката е успешно направена!",
    name_on_card: "Име на картичка",
    enter_name_on_card: "Внесете го името на картичката",
    card_number: "Број на картичка",
    enter_card_number: "Внесете го бројот на картичката",
    expiration: "Истекување",
    MM_YY: "ММ/ГГ",
    CVC: "CVC",
    enter_cvc: "Внесете го CVC",
    payment_information: "Информации за плаќање",
    nameOnCard: "Потребно е името на картичката.",
    cardNumber: "Невалиден број на картичка.",
    invalid_expiration:
      "Невалиден датум на истекување. Користете формат ММ/ГГ и осигурајте се дека картичката не е истечена.",
    invalid_cvc: "Невалиден CVC. Треба да биде 3 или 4 цифри.",
    reservation_datetime_title: "Резервирајте термин",
    reservation_date_label: "Датум",
    reservation_time_label: "Време",
    reservation_datetime_description:
      "Ве молиме, резервирајте термин за вашата услуга. Ние ќе ве контактираме за да ја потврдиме вашата резервација.",
    date_of_reservation: "Резервација",
    time_of_reservation: "Време",
    pending: "На чекање",
    confirmed: "Потврдено",
    completed: "Завршено",
    cancelled: "Откажано",
    choose_time: "Изберете време",
    cancel: "Откажи",
    ok: "Потврди",
    choose_date: "Изберете датум",
    user: "Корисник",
    order_deleted: "Нарачката е избришана.",
    privacy_policy: "Политика за приватност",
    terms_of_service: "Услови за користење",   
    terms_of_service_register: "Условите за користење",
    privacy_intro: "Ние ја почитуваме вашата приватност и сме посветени на заштита на вашите лични податоци. Кога купувате кај нас, ги собираме само информациите потребни за обработка на нарачки, подобрување на вашето искуство и обезбедување корисничка поддршка.",
    information_we_collect: "Кои информации ги собираме",
    info_collect_name_email: "- Име, е-маил, телефон и адреса за испорака при нарачка.",
    info_collect_payment_details: "- Детали за плаќање (се обработуваат безбедно преку надворешни платежни системи).",
    info_collect_optional: "- Дополнителни информации што доброволно ги давате, како преференци или детали за сметка.",
    how_we_use_your_information: "Како ги користиме вашите информации",
    use_order_processing: "- За обработка и испорака на вашите нарачки.",
    use_communication: "- За комуникација во врска со нарачки, промоции или новости.",
    use_improvement: "- За подобрување на производите, услугите и искуството на веб-страницата.",
    how_we_protect_your_information: "Како ги заштитуваме вашите информации",
    protect_info_text: "Користиме безбедносни системи и ги следиме индустриските стандарди за заштита на вашите податоци. Никогаш не ги продаваме, изнајмуваме или споделуваме вашите информации со трети страни, освен кога е потребно за завршување на нарачката (пример: испорака или плаќање).",
    your_rights: "Ваши права",
    your_rights_text: "Може да побарате пристап, исправка или бришење на вашите лични податоци во секое време преку контакт со нас на:",

    terms_of_service: "Услови за користење",
    tos_intro: "Добредојдовте во Kika Makeup Academy. Со пристап или користење на нашата веб-страница и услуги, се согласувате да ги почитувате овие Услови за користење. Ве молиме внимателно прочитајте ги пред да ја користите нашата платформа.",
    user_responsibilities: "Одговорности на корисникот",
    user_responsibility_1: "- Вие сте одговорни за сите активности извршени на вашата сметка.",
    user_responsibility_2: "- Не смее да ја користите веб-страницата за незаконски или забранети цели.",
    user_responsibility_3: "- Треба да обезбедите точни и ажурирани информации при регистрација или поставување на нарачки.",
    account_security: "Сметка и безбедност",
    account_security_1: "- Чувајте ги вашите акредитиви за сметката безбедни и доверливи.",
    account_security_2: "- Веднаш известете не ако се сомневате на неовластен пристап до вашата сметка.",
    orders_payments: "Нарачки и плаќања",
    orders_payments_1: "- Сите нарачки се тема на прифаќање и достапност.",
    orders_payments_2: "- Плаќањата се обработуваат безбедно преку трети лица провајдери.",
    orders_payments_3: "- Вие сте одговорни за сите даноци, давачки или такси поврзани со вашите купувања.",
    changes: "Промени во условите",
    changes_text: "Kika Makeup Academy може да ги ажурира овие Услови за користење во секое време. Продолженото користење на нашите услуги се смета за прифаќање на ажурираните услови.",
    limitation_of_liability: "Ограничување на одговорност",
    limitation_text: "Kika Makeup Academy не е одговорен за индиректни, случајни или последователни штети што произлегуваат од користењето на нашата веб-страница или услуги.",
    governing_law: "Применливо право",
    governing_law_text: "Овие Услови за користење се регулирани со законите на Македонија. Сите спорови ќе се решаваат согласно применливото законодавство.",
    contact: "Контакт",
    contact_text: "За било какви прашања во врска со овие Услови за користење, ве молиме контактирајте не на: ",
    back_to_account: "Назад во мој профил",   
    invalid_credentials: "Погрешен емаил или лозинка.",
    user_not_found: "Не постои корисник со оваа емаил адреса.",
    email_in_use: "Овој емаил веќе е регистриран.",
    too_many_requests: "Преголем број обиди. Обидете се повторно подоцна.",
    network_error: "Грешка во мрежата. Проверете ја вашата конекција.",
    something_went_wrong: "Настана грешка. Обидете се повторно.",
    coupon_discount: "Попуст",
    coupon_applied: "Купонот е применет успешно!",
    order_preview: "Преглед на нарачка",
    back_home: "Дома",
    comingSoon: "Веб-страницата наскоро ќе биде достапна",
    confirm_deletion: "Потврди бришење",
    are_you_sure_delete_order: "Дали сте сигурни дека сакате да ја избришете оваа нарачка?",
    yes_delete: "Да, избриши",
    financial_reports: "Финансиски извештаи",
    revenue_by_payment_method: "Приход по метод на плаќање",
    revenue_by_status: "Приход по статус на нарачка",  
    payment_cash: "Плаќање на лице место",
    select_country: "Изберете држава",
    select_city: "Изберете град",
    confirm_logout: "Одјави се",
    are_you_sure_logout: "Дали сте сигурни дека сакате да се одјавите од вашиот профил?",
    yes_logout: "Да, одјави се",
    financial_reports: "Финансиски Извештаи",
    total_orders: "Вкупно Нарачки",
    total_revenue: "Вкупен Приход",
    avg_order_value: "Просечна Вредност",
    order_success_rate: "Стапка на Успех",
    daily_revenue_trend: "Дневен Приход",
    last_7_days: "Последни 7 Дена",
    last_30_days: "Последни 30 Дена",
    last_90_days: "Последни 90 Дена",
    monthly_revenue: "Месечен Приход",
    yearly_comparison: "Годишна Споредба",
    top_products: "Најпродавани Услуги",
    product_name: "Име на Услуга",
    quantity_sold: "Продадено Количество",
    revenue: "Приход",
    download_pdf: "Преземи PDF",
    preparing_pdf: "Се подготвува PDF...",
    generated_on: "Генерирано на",
    generated_by: "Генерирано од Вашата Компанија",
    all_time_orders: "Сите нарачки",
    gross_revenue: "Вкупен приход",
    per_order_average: "Просек по нарачка",
    confirmed: "Потврденo",
    confirmed_analysis: "Потврдени",
    analysis: "Анализа",
    daily_revenue_description: "Прикажува трендови на приходи за избраниот период",
    monthly_revenue_description: "Месечен распоред на приходи за избраната година",
    yearly_comparison_description: "Споредба на приходи по години",
    top_products_description: "Најпродавани производи рангирани по вкупен приход",
    revenue_by_status_description: "Прикажува приходи распределени по статус на нарачки",
    revenue_by_payment_method_description: "Прикажува приходи распределени по метод на плаќање",
    payment_method: "Метод на плаќање",
    amount: "Износ",
    count: "Број",
    avg_price: "Просечна цена",
    detailed_daily_breakdown: "Детален Дневен Преглед",
    days: "денови",
    date: "Датум",
    orders: "Нарачки",
    revenue: "Приход",
    total: "Вкупно",
    avg_daily_revenue: "Просечен Дневен Приход",
    best_day: "Најдобар Ден",
    avg_orders_per_day: "Просечни Нарачки/Ден",
    detailed_monthly_breakdown: "Детален Месечен Преглед",
    months: "месеци",
    month: "Месец",
    orders: "Нарачки",
    revenue: "Приход",
    avg_per_day: "Просек на ден",
    total: "Вкупно",
    avg_monthly_revenue: "Просечен Месечен Приход",
    best_month: "Најдобар Месец",
    total_orders_year: "Вкупно Нарачки (Година)",
    avg_monthly_orders: "Просечни Месечни Нарачки",
    detailed_yearly_breakdown: "Детален Годишен Преглед",
    years: "години",
    year: "Година",
    orders: "Нарачки",
    revenue: "Приход",
    growth: "Раст",
    avg_monthly: "Просек Месечно",
    total: "Вкупно",
    total_years: "Вкупно Години",
    best_year: "Најдобра Година",
    avg_yearly_revenue: "Просечен Годишен Приход",
    overall_growth: "Вкупен Раст",
    previous: "Прет.",
    next: "След.",
    showing: "Прикажани",
    to: "до",
    of: "од",
    orders: "Нарачки",
    search: "Пребарување",
    search_orders: "Пребарај нарачки...",
    filter_by_status: "Статус",
    all_statuses: "Сите статуси",
    search_order_or_user: "Пребарај нарачка или корисник...",
    filter_by_payment: "Плаќање",
    all_payments: "Сите плаќања",
    filter_by_year: "Година",
    all_years: "Сите години",
    please_confirm_your_password: "Ве молиме, потврдете ја вашата лозинка пред да продолжите.",
    password_must_contain_letter_and_number: "Лозинката мора да содржи барем една голема буква и еден број.",
    please_enter_your_first_name: "Ве молиме, внесете го вашето име.",
    please_enter_your_last_name: "Ве молиме, внесете го вашето презиме.",
    first_name_too_short: "Име мора да содржи најмалку 2 карактери.",
    last_name_too_short: "Презиме мора да содржи најмалку 2 карактери.",
    i_accept: "Се согласувам со ",
    and: " и ",
    coupon_min_total: "Вкупниот износ на кошничката треба да надмине 2999 ден. за да се примени купонот",
    users: "Корисници",   
    total_users: "Вкупно корисници",
    no_users_found: "Нема пронајдено корисници",
    search_user_name_email: "Пребарај по име или email...",
    filter_by_role: "Улога",
    all_roles: "Сите улоги",
    name: "Име",
    phone: "Телефон",
    city: "Град",
    country: "Држава",
    admins: "Администратори",
    guests: "Гости",
    role: "Улога",
    coupon: "Купон",
    admin: "Админ",
    guest: "Гостин",
    continue_with_phone: "Продолжете со телефон",
    enter_your_phone_number: "Внесете го вашиот телефонски број",
    enter_verification_code: "Внесете го кодот за верификација",
  },
};

const LocalizationContext = createContext();

export const useLocalization = () => {
  return useContext(LocalizationContext);
};

export const LocalizationProvider = ({ children }) => {
  const savedLang = localStorage.getItem("language") || "mk";
  const [language, setLanguage] = useState(savedLang); // Tracks the current language

  useEffect(() => {
    const savedLang = localStorage.getItem("language");
    if (savedLang && (savedLang === "mk" || savedLang === "en")) {
      setLanguage(savedLang);
    } else {
      setLanguage("mk"); // fallback to default
      localStorage.setItem("language", "mk");
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    document.body.style.fontFamily = fonts[language] || fonts.en;
  }, [language]);

  const changeLanguage = (lang) => {
    if (lang === "mk" || lang === "en") {
      setLanguage(lang);
    }
  };

  const t = (key) => {
    return (translations[language] && translations[language][key]) || key;
  };

  return (
    <LocalizationContext.Provider
      value={{ changeLanguage, t, currentLanguage: language }}
    >
      {children}
    </LocalizationContext.Provider>
  );
};

export default LocalizationContext;
