import React, { createContext, useContext, useState, useEffect } from 'react';

const fonts = {
  en: "'Dancing Script', cursive", 
  mk: "'Caveat', cursive",   
};

const translations = {
  en: {
    english: "English",
    macedonian: "Macedonian",
    order_online_call: "Order Online Call",
    signup_login: "Sign Up / Login",
    title: "Kika Makeup and Beauty Academy",
    spring_summer: "Spring summer 2024",
    find_your_style: "Find your style. Fall fashion 2024",
    shop_now: "Shop Now",
    men_collection: "MEN COLLECTION",
    sport_collection: "SPORT COLLECTION",
    women_collection: "WOMEN COLLECTION",
    feeling_relax_day: "Feeling relax day, <br /> Enjoy weekend",
    home: "Home",
    shop: "Shop",
    checkout: "Checkout",
    my_account: "My Account",
    login_register: "Login Register",
    about_us: "About Us",
    contact_us: "Contact Us",
    faq: "F.A.Q",
    see_more: "SEE MORE ...",
    read_more: "Read more",
    free_shipping: "FREE SHIPPING",
    free_shipping_description: "On all orders over $75.00",
    free_returns: "FREE RETURNS",
    free_returns_description: "30 days money back guarantee",
    secure_payment: "SECURE PAYMENT",
    brand_name: "makeupbykika",
    all_rights_reserved: "All Rights Reserved",
    about: "ABOUT",
    about_us: "About us",
    store_location: "Store location",
    contact: "Contact",
    orders_tracking: "Orders tracking",
    useful_links: "Useful links",
    returns: "Returns",
    support_policy: "Support Policy",
    size_guide: "Size guide",
    faqs: "FAQs",
    follow_us: "Follow us on",
    subscribe: "Subscribe.",
    subscribe_message: "Subscribe to our newsletter to receive news on updates.",
    email_placeholder: "Your email address",
    contact_title: "Contact",
    home: "Home",
    contact: "Contact",
    contact_detail: "Contact detail",
    come_have_a_look: "COME HAVE A LOOK",
    address: "ADDRESS",
    address_details: "Bul. Turisticka 40, Ohrid - Macedonia 6000",
    contact: "Contact",
    mobile: "Mobile",
    phone: "Phone",
    mail: "Mail",
    hours_of_operation: "HOUR OF OPERATION",
    monday_to_friday: "Monday – Friday",
    weekend_hours: "Sunday & Saturday",
    get_in_touch: "Get in touch",
    first_name: "First Name *",
    email: "Email *",
    subject: "Subject",
    message: "Message",
    submit: "Submit",
    about_page_title: "About",
    home: "Home",
    about: "About",
    simply_or_white: "SIMPLY OR WHITE",
    clever_unique_ideas: "Clever & unique ideas",
    about_page_description: "Lorem ipsum dolor sit amet, consectetur cing elit. Suspe ndisse suscipit sagittis leo sit met condimentum estibulum.",
    store: "STORE",
    our_story: "OUR STORY",
    our_story_link: "OUR STORY",
    address: "ADDRESS",
    address_value: "Bul. Turisticka 40, Ohrid - Macedonia 6000",
    phone: "Phone",
    mobile: "Mobile",
    email: "EMAIL",
    email_value: "contact@makeupbykika.com",
    about_page_extra_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac tortor nec felis fermentum tincidunt.",
    online_store: "online store",
    testimonial_title: "Testimonial",
    our_brands_title: "Our Brands",
    about_us_title: "About Us",
    about_us_description: "At Kika Makeup and Beauty Academy, we are dedicated to inspiring creativity, delivering excellence, and empowering future beauty professionals. Our academy offers comprehensive training in timeless makeup techniques and cutting-edge beauty skills, ensuring our students are prepared for success in a dynamic industry. We focus on nurturing talent and fostering confidence, helping individuals build lasting careers in the world of makeup and beauty.",
    showing: "Showing",
    of: "of",
    result: "result",
    default: "Default",
    price_high_to_low: "Price - High to Low",
    price_low_to_high: "Price - Low to High",
    filter: "Filter",
    categories: "Categories",
    all_categories: "All categories",
    no_categories_found: "No categories found",
    colors: "Colors",
    no_colors_found: "No colors found",
    sizes: "Sizes",
    all_sizes: "All sizes",
    no_sizes_found: "No sizes found",
    tags: "Tags",
    no_tags_found: "No tags found",    
    decor: "Decor",
    fashion: "Fashion",
    men: "Men's Clothing",
    women: "Women's Clothing",
    cosmetics: "Cosmetics",
    furniture: "Furniture",
    perfumes: "Perfumes",
    wearables: "Wearables",
    jewelry: "Jewelry",
    swimsuit: "Swimsuits",
    x: "Small",
    m: "Medium",
    xl: "Large",
    xxl: "Extra Large",
    decor: "Decoration",
    fashion: "Fashion",
    men: "Men's Wear",
    women: "Women's Wear",
    searchPlaceholder: "Search products ...",    
    allCategories: "All categories",
    noCategories: "No categories found",
    colors: "Colors",
    clearFilter: "x",
    noColors: "No colors found",
    popularProducts: "Popular products",
    noPopularProducts: "No products found",
    tags: "Tags",
    noTags: "No tags found",
    added_to_wishlist: "Added to wishlist",
    add_to_wishlist: "Add to wishlist",
    added_to_compare: "Added to compare",
    add_to_compare: "Add to compare",
    quick_view: "Quick view"
  },
  mk: {
    english: "Англиски",
    macedonian: "Македонски",
    order_online_call: "Нарачајте онлајн",
    signup_login: "Регистрирајте се / Најавете се",
    title: "Кика Академија за Шминка и Убавина",
    spring_summer: "Пролет лето 2024",
    find_your_style: "Пронајдете го вашиот стил. Мода за есен 2024",
    shop_now: "Купи сега",
    men_collection: "МAШКА КОЛЕКЦИЈА",
    sport_collection: "СПОРТСКА КОЛЕКЦИЈА",
    women_collection: "ЖЕНСКА КОЛЕКЦИЈА",
    feeling_relax_day: "Опуштен ден, <br /> Уживајте за викендот",
    home: "Дома",
    shop: "Продавница",
    checkout: "Плаќање",
    my_account: "Мој Профил",
    login_register: "Најавете се / Регистрирајте се",
    about_us: "За Нас",
    contact_us: "Контакт",
    faq: "Најчесто поставувани прашања",
    see_more: "Повеќе",
    read_more: "Прочитај повеќе",
    free_shipping: "БЕСПЛАТЕН ПРЕВОЗ",
    free_shipping_description: "На сите нарачки над $75.00",
    free_returns: "БЕСПЛАТНИ ВРАЌАЊА",
    free_returns_description: "Гаранција за поврат на парите во рок од 30 дена",
    secure_payment: "БЕЗБЕДНО ПЛАЌАЊЕ",
    brand_name: "makeupbykika",
    all_rights_reserved: "Сите права се задржани",
    about: "ЗА НАС",
    about_us: "За нас",
    store_location: "Локација на продавница",
    contact: "Контакт",
    orders_tracking: "Следење на нарачки",
    useful_links: "Линкови",
    returns: "Враќања",
    support_policy: "Политика за поддршка",
    size_guide: "Водич за големини",
    faqs: "Најчесто поставувани прашања",
    follow_us: "Следете не на",
    subscribe: "Претплатете се.",
    subscribe_message: "Претплатете се на нашиот билтен за да добивате новости за ажурирања.",
    email_placeholder: "Вашата email адреса",
    contact_title: "Контакт",
    home: "Дома",
    contact: "Контакт",
    contact_detail: "Детали за контакт",
    come_have_a_look: "ДОЈДЕТЕ И ПОГЛЕДНЕТЕ",
    address: "АДРЕСА",
    address_details: "Бул. Туристичка 40, Охрид - Северна Македонија 6000",
    contact: "Контакт",
    mobile: "Мобилен",
    phone: "Телефон",
    mail: "Пошта",
    hours_of_operation: "РАБОТНО ВРЕМЕ",
    monday_to_friday: "Понеделник – Петок",
    weekend_hours: "Недела & Сабота",
    get_in_touch: "Контактирајте не",
    first_name: "Име *",
    email: "Е-пошта *",
    subject: "Предмет",
    message: "Порака",
    submit: "Испрати",
    about_page_title: "За нас",
    home: "Дома",
    about: "За нас",
    simply_or_white: "ЕДНОСТАВНО ИЛИ БЕЛО",
    clever_unique_ideas: "Паметни и уникатни идеи",
    about_page_description: "За нас - Кика Makeup and Beauty Academy",
    store: "ДОМА",
    our_story: "НАШАТА ИСТОРИЈА",
    our_story_link: "НАШАТА ИСТОРИЈА",
    address: "АДРЕСА",
    address_value: "Бул. Туристичка 40, Охрид - Северна Македонија 6000",
    phone: "Телефон",
    mobile: "Мобилен",
    email: "Е-ПОШТА",
    email_value: "contact@makeupbykika.com",
    about_page_extra_description: "Добредојдовте во Кика Makeup and Beauty Academy, место каде што креативноста, иновацијата и професионализмот се комбинираат за да ги подготват идните експерти во индустријата за убавина. Наша мисија е да им овозможиме на нашите студенти најдобра обука и практични вештини кои ќе ги постават на патот кон успехот. Како академија посветена на шминкањето и убавината, нудиме сеопфатни курсеви кои опфаќаат не само основите на шминкањето, туку и напредни техники кои се актуелни на глобалниот пазар. Нашата програма е дизајнирана да ги поттикне креативните потенцијали на нашите студенти и да ги развие во високо квалификувани професионалци кои можат да се справат со секој предизвик во индустријата. Во Кика Makeup and Beauty Academy, го цениме индивидуалниот пристап и се стремиме да создадеме поттикнувачка и инспиративна средина за секој студент. Нашите курсеви се фокусирани на развојот на техниките за шминкање, како и на важноста на самодовербата и креативноста, што е клучно за градење успешни кариера во оваа динамична индустрија. Без разлика дали сакате да станете професионален шминкер, козметичар или да се усовршите во најновите трендови на убавина, нашата академија е тука за да ве води на тој пат и да ви овозможи највисоките стандарди на обука.",
    online_store: "онлајн продавница",
    testimonial_title: "Лични искуства",
    our_brands_title: "Брендови",
    about_us_title: "За Нас",
    about_us_description: "Добредојдовте во Кика Makeup and Beauty Academy, место каде што креативноста, иновацијата и професионализмот се комбинираат за да ги подготват идните експерти во индустријата за убавина. Наша мисија е да им овозможиме на нашите студенти најдобра обука и практични вештини кои ќе ги постават на патот кон успехот. Како академија посветена на шминкањето и убавината, нудиме сеопфатни курсеви кои опфаќаат не само основите на шминкањето, туку и напредни техники кои се актуелни на глобалниот пазар.",
    showing: "Прикажани",
    of: "од",
    result: "резултати",
    default: "По првобитна поставеност",
    price_high_to_low: "Цена - Од висока до ниска",
    price_low_to_high: "Цена - Од ниска до висока",
    filter: "Филтер",
    categories: "Категории",
    all_categories: "Сите категории",
    no_categories_found: "Нема категории",
    colors: "Бои",
    no_colors_found: "Нема бои",
    sizes: "Големини",
    all_sizes: "Сите големини",
    no_sizes_found: "Нема големини",
    tags: "Тагови",
    no_tags_found: "Нема тагови",    
    decor: "Декор",
    fashion: "Мода",
    men: "Мушка облека",
    women: "Женска облека",
    cosmetics: "Козметика",
    furniture: "Мебел",
    perfumes: "Парфеми",
    wearables: "Носиви уреди",
    jewelry: "Накит",
    swimsuit: "Костуми за капење",
    x: "Мала",
    m: "Средна",
    xl: "Голема",
    xxl: "Екстра голема",
    decor: "Декорација",
    fashion: "Мода",
    men: "Мажка облека",
    women: "Женска облека",
    searchPlaceholder: "Пребарување на производи ...",
    categories: "Категории",
    allCategories: "Сите категории",
    noCategories: "Нема категории",
    colors: "Бои",
    clearFilter: "x",
    noColors: "Нема бои",
    popularProducts: "Популарни производи",
    noPopularProducts: "Нема производи",
    tags: "Ознаки",
    noTags: "Нема ознаки",
    added_to_wishlist: "Додадено во листата на желби",
    add_to_wishlist: "Додади во листата на желби",
    added_to_compare: "Додадено за споредба",
    add_to_compare: "Додади за споредба",
    quick_view: "Брз преглед"
  }
};

const LocalizationContext = createContext();

export const useLocalization = () => {
  return useContext(LocalizationContext);
};

export const LocalizationProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');  // Tracks the current language

  useEffect(() => {
    document.body.style.fontFamily = fonts[language] || fonts.en; 
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const t = (key) => {
    return translations[language][key] || key;  // default to key if not found
  };

  return (
    <LocalizationContext.Provider value={{ changeLanguage, t, currentLanguage: language }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export default LocalizationContext;